// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoItem2.Infrastructure;

#nullable disable

namespace ToDoItem2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240729165146_todo1")]
    partial class todo1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoItem2.Domain.ToDoItem", b =>
                {
                    b.Property<int>("taskNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskNum"));

                    b.Property<bool>("done")
                        .HasColumnType("bit");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("taskNum");

                    b.HasIndex("userId");

                    b.ToTable("toDoItems");
                });

            modelBuilder.Entity("ToDoItem2.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoItem2.Domain.ToDoItem", b =>
                {
                    b.HasOne("ToDoItem2.Domain.User", "user")
                        .WithMany("toDoItems")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ToDoItem2.Domain.User", b =>
                {
                    b.Navigation("toDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
