// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoItem2.Infrastructure;

#nullable disable

namespace ToDoItem2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoItem2.Domain.ToDoItem", b =>
                {
                    b.Property<int>("taskNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("taskNum"));

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("done")
                        .HasColumnType("bit");

                    b.Property<string>("taskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("taskNum");

                    b.HasIndex("UserId");

                    b.ToTable("toDoItems");

                    b.HasData(
                        new
                        {
                            taskNum = 1,
                            done = false,
                            taskName = "Task 1"
                        },
                        new
                        {
                            taskNum = 2,
                            done = false,
                            taskName = "Task 2"
                        },
                        new
                        {
                            taskNum = 3,
                            done = false,
                            taskName = "Task 3"
                        });
                });

            modelBuilder.Entity("ToDoItem2.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToDoItem2.Domain.ToDoItem", b =>
                {
                    b.HasOne("ToDoItem2.Domain.User", null)
                        .WithMany("toDoItems")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ToDoItem2.Domain.User", b =>
                {
                    b.Navigation("toDoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
